# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b5795d96213b5ee5bfd512f6da9fabc2d5611083978b5b88706d5ca240a384464aac33d7b01b0a0b26bbb2668a65ad269a2467f900ef18dde11beff5cf2b76e

test:
  secret_key_base: 6e3b846d612e614fee40914c3438ce2a7a894b1046e759fc3644bb6ee57d420324c9216ba9408aab79e9adc055d58e54ea464fa8ad75d3262a7f6abcc52fda66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
